//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Лангуаге
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string product_article { get; set; }
        public string name { get; set; }
        public string product_type { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<decimal> min_price_for_agent { get; set; }
        public Nullable<decimal> weight_without_packaging { get; set; }
        public Nullable<decimal> weight_with_packaging { get; set; }
        public Nullable<bool> quality_certificate { get; set; }
    }
}
